"""add groupID to groupphaseusers table

Revision ID: 0e38febe8725
Revises: d7c76c0f5862
Create Date: 2020-10-14 16:53:59.816441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e38febe8725'
down_revision = 'd7c76c0f5862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupphase_users', sa.Column('groupID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupphase_users', 'groupID')
    # ### end Alembic commands ###
