"""Tournaments

Revision ID: 370497031613
Revises: f1a5ab97b1db
Create Date: 2020-11-02 09:32:20.371475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370497031613'
down_revision = 'f1a5ab97b1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('game_role', sa.BigInteger(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('registration_expires', sa.DateTime(), nullable=False),
    sa.Column('voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('text_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('tournament_teams',
    sa.Column('reaction', sa.Text(), nullable=False),
    sa.Column('tournament_message_id', sa.BigInteger(), nullable=False),
    sa.Column('voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('text_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_message_id'], ['tournaments.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaction', 'tournament_message_id')
    )
    op.create_table('tournament_team_members',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('team_reaction', sa.Text(), nullable=False),
    sa.Column('tournament_message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['team_reaction', 'tournament_message_id'], ['tournament_teams.reaction', 'tournament_teams.tournament_message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'team_reaction', 'tournament_message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_team_members')
    op.drop_table('tournament_teams')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
