"""add wasShuffled

Revision ID: 40f4adab8f28
Revises: 410c6b08a575
Create Date: 2020-10-25 18:50:04.564167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f4adab8f28'
down_revision = '410c6b08a575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupphase_users', sa.Column('wasShuffled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupphase_users', 'wasShuffled')
    # ### end Alembic commands ###
