"""create speechlist table

Revision ID: 410c6b08a575
Revises: 417702862440
Create Date: 2020-10-24 17:51:06.557552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410c6b08a575'
down_revision = '417702862440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speechlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=True),
    sa.Column('prio', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speechlists')
    # ### end Alembic commands ###
