"""create example table

Revision ID: 951d8f1d4d20
Revises: f1a5ab97b1db
Create Date: 2020-11-07 15:08:14.234757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951d8f1d4d20'
down_revision = 'f1a5ab97b1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ctx_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubs')
    # ### end Alembic commands ###
