"""remove old tables

Revision ID: 9a8419efe9ec
Revises: 096c9c704e25
Create Date: 2020-10-11 19:20:53.401216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a8419efe9ec'
down_revision = '096c9c704e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications_games')
    op.drop_table('applications')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('gameID', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('roleID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gameID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applications',
    sa.Column('applicationID', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('applicationID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applications_games',
    sa.Column('applicationID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('gameID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applicationID'], ['applications.applicationID'], name='applications_games_ibfk_1'),
    sa.ForeignKeyConstraint(['gameID'], ['games.gameID'], name='applications_games_ibfk_2'),
    sa.PrimaryKeyConstraint('applicationID', 'gameID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
