"""create speechlist table

Revision ID: ad517d449c9c
Revises: 0e38febe8725
Create Date: 2020-10-17 18:29:59.055103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad517d449c9c'
down_revision = '0e38febe8725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speechlists',
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speechlists')
    # ### end Alembic commands ###
