"""create group table

Revision ID: bbf800f50484
Revises: 9a8419efe9ec
Create Date: 2020-10-12 15:48:00.480395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf800f50484'
down_revision = '9a8419efe9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.BigInteger(), nullable=True),
    sa.Column('voiceChannel', sa.BigInteger(), nullable=True),
    sa.Column('textChannel', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
