"""create groupphaseusers table

Revision ID: d7c76c0f5862
Revises: b3c8d398f765
Create Date: 2020-10-14 16:38:14.722705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c76c0f5862'
down_revision = 'b3c8d398f765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupphase_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupphase_users')
    # ### end Alembic commands ###
